---
base: &base
  name: 'test_app_2'
  description: 'test desc'
  app_id: '1234sdlfk'
  solution_stack: '64bit Amazon Linux running Ruby 1.9.3'

  options:
    aws:autoscaling:launchconfiguration:
      EC2KeyName: 'id_rsa'

  regions:
    us-west-2:
      options:
        aws:elasticbeanstalk:application:environment:
          PARAM1: 'a value'
      
    us-east-1:

environments:
  production:
    <<: *base
    name: 'test_app_prod'

  test:
    <<: *base

  staging:
    <<: *base

  development:
    <<: *base
