aws: &aws
  access_key_id: 'AKIAIZGLLSJXZOOR5KSQ'
  secret_access_key: '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'
  #dynamo_db_endpoint: 'dynamodb.us-east-1.amazonaws.com'

local: &local
  access_key_id: 'xxx'
  secret_access_key: 'xxx'
  dynamo_db_endpoint: 'localhost'
  dynamo_db_port: 4567
  use_ssl: false

development:
  <<: *aws

test:
  <<: *local

# NOT SET UP!

production:
  <<: *aws

sandbox:
  <<: *local
